[workspace]
members = ["."]

[package]
name = "bulldog-bootloader"
version = "0.1.0"
edition = "2024"

[dependencies]
uefi = "0.28.0"
log = "0.4"
boot-proto = { path = "../boot-proto" }

[[bin]]
name = "bulldog-bootloader"
path = "src/main.rs"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
